frequency: 1  # Study status publishing frequency
study_name: "KATE_AA"
task_ids: [
  "1_green_line_force_right_40",
  "2_green_line_force_right_60",
  "3_green_line_force_right_80",
  "4_green_line",
  "5_green_line_force_left_40",
  "6_green_line_force_left_60",
  "7_green_line_force_left_80",
  "8_green_line_force_both_40",
  "9_green_line_force_both_60",
  "10_green_line_force_both_80",
  "11_circle",
  "12_yellow_line",
  "13_yellow_line_rotation",
  "14_yellow_line_rotations",
  "15_yellow_line_force_right_40",
  "16_yellow_line_force_right_60",
  "17_yellow_line_force_right_80",
  "18_yellow_line_force_both_40",
  "19_yellow_line_force_both_60",
  "20_yellow_line_force_both_80",
  "END"]
user_id_prefix: "U"
user_id_length: 3  # e.g. 001 (max: 999)
  
# run_command_on_task_change: ["echo_name"]

# String has format:
# study_name + output_string_separator +
# user_id_prefix + user_id + output_string_separator +
# task_id + "-" + trial
output_string_separator: "_"

use_led_output: True

manager_status_file: "/status/user_study_manager.status" # Path relative to the package directory
