frequency: 1  # Study status publishing frequency
study_name: "KATE_BO"
scenario_folder_path: "/home/robotrainer/workspace/docker/robotrainer_docker_bayesian_optimization/data/scenarios"
bag_folder_path: "/home/robotrainer/workspace/docker/robotrainer_docker_bayesian_optimization/data/bags"
initial_scenario: "initial_scenario"
user_id_prefix: "U"
user_id_length: 3  # e.g. 001 (max: 999)
  
# run_command_on_task_change: ["echo_name"]

# String has format:
# study_name + output_string_separator +
# user_id_prefix + user_id + output_string_separator +
# task_id + "-" + trial
output_string_separator: "_"

use_led_output: True

manager_status_file: "/status/user_study_manager.status" # Path relative to the package directory
